services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" 
      - "15672:15672" 
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  invoice-creation-service:
    build:
      context: ./invoice-creation-service
    container_name: invoice-creation-service
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - MONGODB_URI=mongodb://mongo:27017/invoice-db
      - RABBITMQ_URI=amqp://rabbitmq:5672
    ports:
      - "3002:3000" 

  email-sender-service:
    build:
      context: ./email-sender-service
    container_name: email-sender-service
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URI=amqp://rabbitmq:5672
    ports:
      - "3003:3001" 

volumes:
  mongo-data:
  rabbitmq-data:
